version: "3.9"
services:
  scrapper-guard-api:
    image: erayaydogdu/scrapper-guard-api
    network_mode: "host"
    ports:
      - "5060:5060"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5060/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3