# Push workflow - Only runs manually
name: Docker Image Push

on:
  workflow_dispatch:
    # No inputs needed, running this workflow at all is the approval

jobs:
  push:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/scrapper-guard:latest --platform=linux/arm64
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/scrapper-guard:latest